# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Mac Installer

on:
  release:
    types: [ published ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn -B install --file pom.xml
      - name: Upload DMG to GitHub Actions
        uses: actions/upload-artifact@v3
        with:
          name: DMG file
          path: target/installer/*.dmg
      - name: Upload DMG to Release
        uses: AButler/upload-release-assets@v2.0
        with:
          files: 'target/installer/*.dmg'
          repo-token: ${{ secrets.GITHUB_TOKEN }}