# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Linux Installer

on:
  release:
    types: [ published ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'
          cache: maven
      - name: Install @actions/glob
        run: npm install @actions/glob
      - name: Build with Maven
        run: mvn -B install --file pom.xml
      - name: Upload DEB package to GitHub Actions
        uses: actions/upload-artifact@v3
        with:
          name: Installer files
          path: target/installer/*.deb
      - name: Upload DEB to Release
        uses: Roang-zero1/github-upload-release-artifacts-action@v2
        with:
          args: target/installer/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}