# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Mac Installer

on:
  release:
    types: [ published ]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'adopt'
          cache: maven
      - name: Build with Maven
        run: mvn -B install --file pom.xml
      - name: Upload DMG
        uses: actions/upload-artifact@v3
        with:
          name: DMG file
          path: target/installer/*.dmg
      - name: Attach DMG to release
        uses: actions/github-script@v4
        with:
          script: |
            const release_id = core.getInput("release_id");
            const artifacts = await glob.glob("target/installer/*.dmg");
            const { data: upload_url } = await github.repos.uploadReleaseAsset({
              url: `https://uploads.github.com/repos/${context.repo.owner}/${context.repo.repo}/releases/${release_id}/assets{?name,label}`,
              headers: {
                "content-type": "application/octet-stream",
                "content-length": artifacts[0].size,
              },
              name: artifacts[0].name,
              data: artifacts[0].content,
            });